config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "to_dos#index"
  resources :to_dos, only: [:index, :create, :destroy, :update, :edit, :new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/to_do.rb
# frozen_string_literal: true

class ToDo < ApplicationRecord
  validates :title, presence: true
  validates :title, length: { minimum: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/to_dos_controller.rb
# frozen_string_literal: true

class ToDosController < ApplicationController
  def index
    @to_dos = ToDo.all
  end

  def new
    @to_do = ToDo.new
  end

  def create
    @to_do = ToDo.new(to_do_params)
    if @to_do.save
      respond_to do |format|
        format.html { redirect_to to_dos_path }
        format.turbo_stream
      end
    else
      render turbo_stream: turbo_stream.update("errors", partial: "shared/error_messages", locals: { errors: @to_do.errors.full_messages }), status: :unprocessable_entity
    end
  end

  def edit
    @to_do = ToDo.find(params[:id])
  end

  def update
    @to_do = ToDo.find(params[:id])
    if @to_do.update(to_do_params)
      redirect_to to_dos_path
    else
      render :edit, status: 422
    end
  end

  def destroy
    @to_do = ToDo.find(params[:id])
    @to_do.destroy

    respond_to do |format|
      format.html { redirect_to to_dos_path }
      format.turbo_stream
    end
  end

  private

  def to_do_params
    params.require(:to_do).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-50">
  <head>
    <title>ToDos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="mt-40 mx-auto max-w-7xl sm:px-6 lg:px-8">
      <%= yield %>
      <%= turbo_frame_tag "modal" %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<div class="rounded-md bg-red-50 p-4" id="errors">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
      </svg>
    </div>
    <div class="ml-3">
      <h3 class="text-sm font-medium text-red-800">Oops</h3>
      <div class="mt-2 text-sm text-red-700">
        <p><%= errors %></p>
      </div>
    </div>
  </div>
</div>

app/views/to_dos/_form.html.erb
<%= form_with(model: to_do, url: to_do.persisted? ? to_do_path(to_do) : to_dos_path, method: to_do.persisted? ? :patch : :post, class: "mt-20") do |form| %>
  <% if form.object.errors.any? %>
    <div id="error_explanation">
      <div class="rounded-md bg-red-50 p-4 mb-8 max-w-lg">
        <div class="flex">
          <div class="flex-shrink-0">
            <svg class="h-5 w-5 text-red-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.28 7.22a.75.75 0 00-1.06 1.06L8.94 10l-1.72 1.72a.75.75 0 101.06 1.06L10 11.06l1.72 1.72a.75.75 0 101.06-1.06L11.06 10l1.72-1.72a.75.75 0 00-1.06-1.06L10 8.94 8.28 7.22z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800"><%= pluralize(form.object.errors.count, "error") %> prohibited this item from being saved:</h3>
            <div class="mt-2 text-sm text-red-700">
              <% form.object.errors.full_messages.each do |message| %>
                <p><%= message %></p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="field max-w-sm flex">
    <%= form.text_field :title, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6 mr-2", placeholder:" Your to-do title" %>
    <%= link_to "Cancel", to_dos_path, class: "mr-1 text-white right-2.5 bottom-2.5 bg-gray-400 hover:bg-gray-500 focus:ring-4 font-medium rounded-lg text-sm px-4 py-2" if to_do.persisted? %>
    <%= form.submit to_do.persisted? ? "Edit" : "Create", class: "text-white right-2.5 bottom-2.5 bg-indigo-500 hover:bg-indigo-600 focus:ring-4 font-medium rounded-lg text-sm px-4 py-2" %>
  </div>
<% end %>

app/views/to_dos/_to_do.html.erb
<%= turbo_frame_tag to_do do %>
  <li class="flex items-center justify-between gap-x-6 py-5">
    <div class="min-w-0">
      <div class="flex items-start gap-x-3">
        <h1 class="text-2xl font-extrabold leading-none tracking-tight text-gray-900"><%= to_do.title %></h1>
        <p class="rounded-md whitespace-nowrap mt-0.5 px-1.5 py-0.5 text-xs font-medium ring-1 ring-inset text-green-700 bg-green-50 ring-green-600/20">Complete</p>
      </div>
    </div>
    <div class="flex flex-none items-center gap-x-4">
      <%= link_to edit_to_do_path(to_do) do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-600 hover:text-gray-400">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.862 4.487l1.687-1.688a1.875 1.875 0 112.652 2.652L10.582 16.07a4.5 4.5 0 01-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 011.13-1.897l8.932-8.931zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0115.75 21H5.25A2.25 2.25 0 013 18.75V8.25A2.25 2.25 0 015.25 6H10" />
        </svg>
      <% end %>

      <div class="relative flex-none">
        <%= button_to to_do_path(to_do), method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6 text-gray-600 hover:text-red-400">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
          </svg>
        <% end %>
      </div>
    </div>
  </li>
<% end %>

app/views/to_dos/create.turbo_stream.erb
<%= turbo_stream.prepend "to_dos", partial: "to_dos/to_do", locals: { to_do: @to_do } %>
<%= turbo_stream.update ToDo.new, "" %>

app/views/to_dos/destroy.turbo_stream.erb
<%= turbo_stream.remove @to_do %>

app/views/to_dos/edit.html.erb
<%= turbo_frame_tag @to_do do %>
  <%= render "to_dos/form", to_do: @to_do %>
<% end %>

app/views/to_dos/index.html.erb
<div class="border rounded-md border-gray-200 bg-white px-4 py-5 sm:px-6">
  <div class="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
    <div class="ml-4 mt-2 flex gap-x-4 items-center">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-8 h-8">
        <path fill-rule="evenodd" d="M10.5 3A1.501 1.501 0 009 4.5h6A1.5 1.5 0 0013.5 3h-3zm-2.693.178A3 3 0 0110.5 1.5h3a3 3 0 012.694 1.678c.497.042.992.092 1.486.15 1.497.173 2.57 1.46 2.57 2.929V19.5a3 3 0 01-3 3H6.75a3 3 0 01-3-3V6.257c0-1.47 1.073-2.756 2.57-2.93.493-.057.989-.107 1.487-.15z" clip-rule="evenodd" />
      </svg>
      <h3 class="text-5xl font-semibold leading-6 text-gray-900">to-dos list</h3>
    </div>
    <div class="ml-4 mt-2 flex-shrink-0">
      <%= link_to "Add +", new_to_do_path, class: "relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: { turbo_frame: "modal" } %>
    </div>
  </div>
</div>

<div class="shadow-md rounded-md">
  <ul role="list" class="divide-y divide-gray-100 pr-4 pl-4">
    <%= turbo_frame_tag "to_dos" do %>
      <%= render @to_dos %>
    <% end %>
  </ul>
</div>

app/views/to_dos/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal" data-controller="modal" data-modal-target="modal" data-action="turbo:submit-end->modal#submitEnd">
    <div class="relative z-10" aria-labelledby="modal-title" role="dialog" aria-modal="true">
      <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity"></div>
  
      <div class="fixed inset-0 z-10 overflow-y-auto">
        <div class="flex min-h-full items-end justify-center p-4 text-center sm:items-center sm:p-0">
          <div class="relative transform overflow-hidden rounded-lg bg-white px-4 pb-4 pt-5 text-left shadow-xl transition-all sm:my-8 sm:w-full sm:max-w-sm sm:p-6 animate-fade-in-up">
          <%= turbo_frame_tag "errors" %>
            <div class="mt-3 text-center sm:mt-5">
              <div class="mt-2">
                <h1 class="mb-4 mt-8 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-3xl">New to-do</h1>
                <%= render "to_dos/form", to_do: @to_do %>
              </div>
            </div>
            <div class="mt-5 sm:mt-6">
              <%= button_to "Go back", "#", class: "inline-flex w-full justify-center rounded-md bg-gray-400 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-300 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: { action: "modal#hideModal" } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>